# Basic ci workflow using github actions
name: unittest

concurrency:
  group: ${{ github.ref }}/unittest
  cancel-in-progress: true

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-unittest.yaml
    - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Jobs to test schema, input json file, and requirements
  multiplex-unittests:
    # Job will run on github-hosted runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pytest pytest-html jsonschema

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          pytest -v --html=report.html --self-contained-html multiplex.py tests/*.py

      - name: Upload html report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
